import { Lead, Organization } from "@/lib/db/types";

export const DEMO_ORGANIZATION: Organization = {
  id: "org_demo",
  name: "Apex Smiles & Healthcare",
  plan_tier: "growth",
  active_leads_limit: 100,
  subscription_status: "active",
};

export const DEMO_LEADS: Lead[] = [
  {
    id: "lead_1",
    org_id: "org_demo",
    name: "Dr. Amanda Vance",
    email: "amanda.vance@example.com",
    phone: "+15552345678",
    source: "gmail",
    status: "new_lead",
    detected_service: "Dental Implants Consult",
    detected_urgency: "high",
    sentiment: "positive",
    requires_approval: true,
    approval_pending: true,
    created_at: new Date(Date.now() - 3600000 * 2),
  },
  {
    id: "lead_2",
    org_id: "org_demo",
    name: "Marcus Sterling",
    email: "marcus@growthmedia.co",
    phone: null,
    source: "webhook",
    status: "contacted",
    detected_service: "Q4 Marketing Retainer",
    detected_urgency: "medium",
    sentiment: "neutral",
    requires_approval: false,
    approval_pending: false,
    created_at: new Date(Date.now() - 3600000 * 12),
  },
  {
    id: "lead_3",
    org_id: "org_demo",
    name: "Chloe Bennett",
    email: "chloe.b@weddingmail.com",
    phone: "+15558901234",
    source: "whatsapp",
    status: "replied",
    detected_service: "October Wedding Photography",
    detected_urgency: "high",
    sentiment: "positive",
    requires_approval: false,
    approval_pending: false,
    created_at: new Date(Date.now() - 3600000 * 24),
  },
  {
    id: "lead_4",
    org_id: "org_demo",
    name: "David O'Connor",
    email: "david@oconnorlaw.com",
    phone: null,
    source: "gmail",
    status: "booked",
    detected_service: "Business Formation Counsel",
    detected_urgency: "medium",
    sentiment: "positive",
    requires_approval: false,
    approval_pending: false,
    created_at: new Date(Date.now() - 3600000 * 48),
  },
  {
    id: "lead_5",
    org_id: "org_demo",
    name: "Robert Henderson",
    email: "robert.h@outlook.com",
    phone: "+15553334444",
    source: "gmail",
    status: "lost",
    detected_service: "Commercial Roofing Estimate",
    detected_urgency: "low",
    sentiment: "objection",
    requires_approval: false,
    approval_pending: false,
    created_at: new Date(Date.now() - 3600000 * 72),
  },
  {
    id: "lead_6",
    org_id: "org_demo",
    name: "Samantha Wright",
    email: "samantha.w@designhaus.io",
    phone: "+15556667788",
    source: "whatsapp",
    status: "new_lead",
    detected_service: "Invisalign Treatment Consultation",
    detected_urgency: "high",
    sentiment: "positive",
    requires_approval: true,
    approval_pending: true,
    created_at: new Date(Date.now() - 3600000 * 4),
  },
];
