/**
 * Server-only follow-up draft composer.
 *
 * Kept separate from `approval.service.ts` (which is imported by client
 * components) because it depends on env, logger, and outbound fetch.
 */
import { Lead } from "@/lib/db/types";
import { env } from "@/lib/env";
import { logger } from "@/lib/logger";
import { generateDraftFollowUpMessage } from "./approval.service";

export interface ComposedFollowUpDraft {
  body: string;
  source: "ai" | "template";
}

/**
 * Composes the follow-up draft for a lead.
 *
 * When an OpenAI-compatible API key is configured, the draft is generated by
 * the LLM; otherwise (or on any LLM failure) it falls back to the vertical
 * template. The returned `source` lets the caller stay honest about which one it is.
 */
export async function composeFollowUpDraft(
  lead: Lead,
  industryOverride?: string,
  orgName?: string | null
): Promise<ComposedFollowUpDraft> {
  const template = generateDraftFollowUpMessage(lead, industryOverride, orgName);

  if (!env.OPENAI_API_KEY) {
    return { body: template, source: "template" };
  }

  try {
    const baseUrl = (env.OPENAI_BASE_URL || "https://api.openai.com/v1").replace(/\/+$/, "");
    const model = env.OPENAI_MODEL || "gpt-4o-mini";
    const firstName = (lead.name || "there").split(" ")[0].trim();

    const response = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model,
        temperature: 0.4,
        max_tokens: 300,
        messages: [
          {
            role: "system",
            content:
              `You write short, warm, professional follow-up emails from the business "${orgName || "our company"}" ` +
              `to a lead who inquired about "${lead.detected_service || "our services"}". ` +
              "Use the lead's first name. Reference their inquiry. Propose one specific next step with a concrete time window. " +
              "No marketing fluff, no placeholders like [NAME], under 120 words. Plain text only.",
          },
          {
            role: "user",
            content: `Lead first name: ${firstName}. Inquiry service: ${lead.detected_service || "general"}. Sentiment: ${lead.sentiment || "neutral"}.`,
          },
        ],
      }),
      signal: AbortSignal.timeout(15000),
    });

    if (!response.ok) {
      const errorText = await response.text();
      logger.warn("LLM draft generation failed; using template draft", {
        service: "DraftService",
        leadId: lead.id,
        status: response.status,
        error: errorText.slice(0, 300),
      });
      return { body: template, source: "template" };
    }

    const data = (await response.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const content = data.choices?.[0]?.message?.content?.trim();

    if (!content) {
      return { body: template, source: "template" };
    }

    return { body: content, source: "ai" };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.warn("LLM draft generation error; using template draft", {
      service: "DraftService",
      leadId: lead.id,
      error: msg,
    });
    return { body: template, source: "template" };
  }
}
